### PR TITLE
ci: also launch tests on i386

### LINKED ISSUE #6: Make sure code can be run on 32 bits version
strconv.IntSize varies from 32 to 64

It can be used to detect

### LINKED ISSUE #46: Support for 32-bit architectures?
Hi.  I'm packaging this for Debian (because the Tillitis TKEY has it as a dependency) and ran into a self test failure on i386:

https://salsa.debian.org/jas/golang-github-ccoveille-go-safecast/-/jobs/6578765

```
# github.com/ccoveille/go-safecast_test [github.com/ccoveille/go-safecast.test]
src/github.com/ccoveille/go-safecast/conversion_test.go:732:43: cannot use math.MaxInt32 + 1 (untyped int constant 2147483648) as int value in struct literal (overflows)
src/github.com/ccoveille/go-safecast/conversion_test.go:733:43: cannot use math.MinInt32 - 1 (untyped int constant -2147483649) as int value in struct literal (overflows)
src/github.com/ccoveille/go-safecast/conversion_test.go:886:43: cannot use math.MaxUint32 + 1 (untyped int constant 4294967296) as int value in struct literal (overflows)
src/github.com/ccoveille/go-safecast/conversion_test.go:943:43: cannot use math.MaxUint32 + 1 (untyped int constant 4294967296) as uint value in struct literal (overflows)
src/github.com/ccoveille/go-safecast/conversion_test.go:1083:43: cannot use math.MaxInt64 + 1 (untyped int constant 9223372036854775808) as uint value in struct literal (overflows)
src/github.com/ccoveille/go-safecast/conversion_test.go:1375:43: cannot use math.MaxInt64 + 1 (untyped int constant 9223372036854775808) as uint value in struct literal (overflows)
FAIL	github.com/ccoveille/go-safecast [build failed]
```

Could you fix this, so the package works on 32-bit platforms too?  Or is this package only for 64-bit architectures?

/Simon

### PR DESCRIPTION
**Pull request by ccoVeille**
Fixes #6
Fixes #46

### CODE REVIEW

**Comment by ccoVeille** [comment]
It's the first time I'm doing that @ldemailly 

what do you think?

**Comment by ccoVeille** [comment]
cc @jas4711 for a follow-up on Debian packaging

**Comment by ccoVeille** [comment]
> It's the first time I'm doing that @ldemailly 
> 
> what do you think?

Could you also take a look @mmorel-35 @yassinebenaid ?

I'm curious about your feedbacks.

File: asserters_test.go [hunk 1]
```diff
@@ -0,0 +1,386 @@
...
+	"strings"
+	"testing"
+
+	"github.com/ccoveille/go-safecast"
+)
+
+// The tests in conversion_all_test.go are the ones that are not architecture dependent
+// The tests in conversion_64bit_test.go complete them for 64-bit systems
+//
+// This architecture dependent file covers the fact, you can reach
```
Comment (yassinebenaid) [inline asserters_test.go:15]: incomplete comment. did you mean:
>// This architecture dependent file covers the fact, you can reach a higher value with int and uint
// on 64-bit systems, but you will get a compile error on 32-bit.
// This is why it needs to be tested in an architecture dependent way.

File: examples_32bit_test.go [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+	"math"
+
+	"github.com/ccoveille/go-safecast"
+)
+
+func ExampleToInt() {
+	a := uint64(42)
+	i, err := safecast.ToInt(a)
+	if err != nil {
+		fmt.Println(err)
```
Comment (yassinebenaid) [inline examples_32bit_test.go:27]: This is me when I see an error written to STDOUT instead of STDERR 😄 :

angry.

can you `fmt.Fprintln(os.Stderr, err)` please !

Comment (yassinebenaid) [reply examples_32bit_test.go:27]: Same for all examples

Comment (ldemailly) [reply examples_32bit_test.go:27]: should be log.Printf() really

Comment (yassinebenaid) [reply examples_32bit_test.go:27]: I totally agree with you, however, I would consider using `panic(err)` in examples rather than `fmt.Println` for errors.

Comment (ccoVeille) [reply examples_32bit_test.go:27]: Thabks guys, I will check and change

**Comment by ccoVeille** [comment]
> I would appreciate a new release eventually!

@jas4711 sure, I'll release once merged

**Comment by jas4711** [comment]
This has some problems even on 64-bit platforms, check test results:

https://tracker.debian.org/pkg/golang-github-ccoveille-go-safecast

This uses dd8172d73d3682a1d793da273cfa2f20c7cb9cac

Good thing it now works on i386 :)

For example arm64 -- https://ci.debian.net/packages/g/golang-github-ccoveille-go-safecast/testing/arm64/54342388/

```
 79s === RUN   TestToInt32/from_float64/positive_out_of_range
 79s     asserters_test.go:230: expected error
 79s --- FAIL: TestToInt32 (0.00s)
 79s     --- PASS: TestToInt32/from_int (0.00s)
...
 79s     --- PASS: TestToInt32/from_uint64 (0.00s)
 79s         --- PASS: TestToInt32/from_uint64/zero (0.00s)
 79s         --- PASS: TestToInt32/from_uint64/positive_within_range (0.00s)
 79s         --- PASS: TestToInt32/from_uint64/positive_out_of_range (0.00s)
 79s     --- FAIL: TestToInt32/from_float32 (0.00s)
 79s         --- PASS: TestToInt32/from_float32/zero (0.00s)
 79s         --- PASS: TestToInt32/from_float32/rounded_value (0.00s)
 79s         --- PASS: TestToInt32/from_float32/positive_within_range (0.00s)
 79s         --- FAIL: TestToInt32/from_float32/positive_out_of_range (0.00s)
 79s     --- FAIL: TestToInt32/from_float64 (0.00s)
 79s         --- PASS: TestToInt32/from_float64/zero (0.00s)
 79s         --- PASS: TestToInt32/from_float64/rounded_value (0.00s)
 79s         --- PASS: TestToInt32/from_float64/positive_within_range (0.00s)
 79s         --- FAIL: TestToInt32/from_float64/positive_out_of_range (0.00s)
 79s === RUN   TestToUint32
```

Could you take a look at the logs?   Seems like the float changes introduced some bugs, before (v1.10.0) it passed on all 64-bit platforms.

File: examples_32bit_test.go (hunk 2 above)
Comment (ccoVeille) [reply examples_32bit_test.go:27]: I checked and none works

- panic would lead to a panic, so the automatic test of the example file will fail
- log.Printn would dump a log date in the ouput

Please note I'm validating the examples with `// Output: ` syntax

https://pkg.go.dev/testing#hdr-Examples

> The package also runs and verifies example code. Example functions may include a concluding line comment that begins with "Output:" and is compared with the standard output of the function when the tests are run. (

I looked for examples in the stdlib

https://pkg.go.dev/strconv@go1.23.3#example-Unquote

I won't play with this and a non-default logger
https://pkg.go.dev/log#Lmsgprefix

I will keep my approach of fmt.Println

**Comment by ccoVeille** [comment]
@jas4711 I added a new commit to try to fix the issue you are facing with float imprecision

d12e3ebc234ab07c0c867db03dbc1d7f9c4a4f78

Could you tell me if if works ?

**Comment by jas4711** [comment]
> @jas4711 I added a new commit to try to fix the issue you are facing with float imprecision
> 
> [d12e3eb](https://github.com/ccoVeille/go-safecast/commit/d12e3ebc234ab07c0c867db03dbc1d7f9c4a4f78)
> 
> Could you tell me if if works ?

I've uploaded 1.1.0+git20241114-1 to Debian and results should arrive here within the next day or so:

https://tracker.debian.org/pkg/golang-github-ccoveille-go-safecast

Please ignore the results for 20241113, they are for the old version.

**Comment by jas4711** [comment]
The build looks good now.  A new release would be great!  Thank you.

**Review by yassinebenaid — APPROVED** [review]
LGTM 🔅

File: examples_32bit_test.go (hunk 2 above)
Comment (ccoVeille) [reply examples_32bit_test.go:27]: @ldemailly @yassinebenaid did you see my explanation ?

**Comment by ccoVeille** [comment]
> The build looks good now.  A new release would be great!  Thank you.

@jas4711 1.2.0 is out

**Comment by jas4711** [comment]
FWIW, 1.2.0 has now been built fine on all architectures, so I can confirm that this is solved.
