### PR TITLE
fix bug with float32 and float64 overflowing integers

### LINKED ISSUE #23: #14 introduced a bug with float overflow
> where is the check for overflow for say uint32
>
and none of the signed overflow are checked

_Originally posted by @ldemailly in https://github.com/ccoVeille/go-safecast/pull/14#issuecomment-2336538178_

> Maybe you are talking about the fact the code will cast math.MaxFloat32 with uint64 and compare it to math.MaxUint32
> This might be the issue you were talking because yes, the code and tests might have a bug.

> Comfirmed https://go.dev/play/p/3DlJcb10eYs

_Originally posted by @ccoVeille in https://github.com/ccoVeille/go-safecast/pull/14#issuecomment-2336549628_

### PR DESCRIPTION
**Pull request by ccoVeille**
- **fix: float overflow when converted to integer** Fixes #23 
- **chore: add new types**
- **chore: split conversion into multiple files**

### CODE REVIEW

File: conversion.go [hunk 1]
```diff
@@ -25,153 +36,239 @@ type Number interface {
...
+		bigger = float64(f) >= float64(boundary)
+	default:
+		bigger = uint64(value) > boundary
+	}
+
+	if bigger {
+		return Error{
+			value:    value,
+			boundary: boundary,
+			err:      fmt.Errorf("%v (%T) is greater than %v", value, value, boundary),
```
Comment (ccoVeille) [inline conversion.go:241]: I'm not happy about this, I will have to refactor a bit

**Comment by ccoVeille** [comment]
I see you added a 👍 is there something missing in term of setting that prevent you to approve via the GitHub feature made for that ?

**Comment by ccoVeille** [comment]
The scope of this PR has been totally revamped, this PR is now only about fixing the bug with floats possibibly overflowing integers

The PR was containing changes about having rror messages, it will be addressed in another PR

**Comment by ldemailly** [comment]
> chore: add new types

isn't that "feat" (though personally I don't use these abbreviations)

File: types.go [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+// This files is highly inspired from https://pkg.go.dev/golang.org/x/exp/constraints
+// I didn't import it as it would have added an unnecessary dependency
+
+// Signed is an alias for all signed integers: int, int8, int16, int32, and int64 types.
+type Signed interface {
+	~int | ~int8 | ~int16 | ~int32 | ~int64
+}
+
+// Unsigned is an alias for all unsigned integers: uint, uint8, uint16, uint32, and uint64 types.
+// TODO: support uintpr
```
Comment (ldemailly) [inline types.go:12]: it's really ez

https://github.com/ldemailly/go-scratch/commit/4608bec5f1ff7a31c85da80072858427006254b4

File: types.go [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+}
+
+// Number is an alias for all integers and floats
+// TODO: consider using complex, but not sure there is a need
+type Number interface {
+	Integer | Float
+}
+
+// Type is an alias for everything that can be converted
+type Type interface {
```
Comment (ldemailly) [inline types.go:34]: Why is that needed vs Number?

File: errors.go [hunk 4]
```diff
@@ -0,0 +1,5 @@
+package safecast
+
+import "errors"
+
+var ErrIntegerOverflow = errors.New("integer overflow")
```
Comment (ldemailly) [inline errors.go:5]: what about float32 overflows?

File: asserters.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+	if value <= 0 {
+		return nil
+	}
+
+	var bigger bool
+	switch f := any(value).(type) {
+	case float32:
+		bigger = float64(f) >= float64(boundary)
+	case float64:
+		bigger = float64(f) >= float64(boundary)
```
Comment (ldemailly) [inline asserters.go:22]: same code? did you mean float32 above? add a test that fails before fixing?

File: asserters.go [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+
+func checkLowerBoundary[T Type](value T, boundary int64) error {
+	if value >= 0 {
+		return nil
+	}
+
+	var smaller bool
+	switch f := any(value).(type) {
+	case float32:
+		smaller = float64(f) <= float64(boundary)
```
Comment (ldemailly) [inline asserters.go:42]: same
```suggestion
		smaller = float32(f) <= float32(boundary)
```

File: asserters.go (hunk 5 above)
Comment (ccoVeille) [reply asserters.go:22]: No it's the right way to do.

I'll add a comment to explain

File: types.go (hunk 2 above)
Comment (ccoVeille) [reply types.go:12]: I wasn't worried 😁 but thanks

File: errors.go (hunk 4 above)
Comment (ccoVeille) [reply errors.go:5]: wording is a pain indeed

But for now, it's OK. I'm only converting as integer, even it I accept float, so for now the wording is OK.

But I'll change it anyway to avoid renaming again later

File: types.go (hunk 3 above)
Comment (ccoVeille) [reply types.go:34]: Look at the commit message 143314ce44215ffa556d20e4ad4de71230c0e200

>We may add the following type later:
>- uintptr
>- string
>- bool

File: asserters.go (hunk 6 above)
Comment (ccoVeille) [reply asserters.go:42]: For now, yes.

But in the future, when I will add a convention to float32, I will need to make sure a provided float64 won't break everything

**Comment by ccoVeille** [comment]
> > chore: add new types
> 
> isn't that "feat" (though personally I don't use these abbreviations)

I'm not adding new type in that commit, I'm somehow renaming it.

I hate conventional commit, but I see a lot of it on GitHub, so I was somehow poisoned. When I'm on GitHub, I use it

File: asserters.go (hunk 5 above)
Comment (ccoVeille) [reply asserters.go:22]: > No it's the right way to do.

Unless I'm wrong 😅

I'll check

File: errors.go (hunk 4 above)
Comment (ccoVeille) [reply errors.go]: I commented accordingly, it should be clearer

File: asserters.go (hunk 5 above)
Comment (ccoVeille) [reply asserters.go]: No, it's normal.

I added comments, it should be clearer

File: asserters.go (hunk 6 above)
Comment (ccoVeille) [reply asserters.go]: No it's OK, I added comments

Comment (ldemailly) [reply asserters.go]: I think it's an issue the float case detects the funnyness with 52 bits boundary, but it's lower on float32 so I think it won't work (but I haven't written a test but it's basically that boundary bug but for float32)
